In [8]:
import pandas as pd

In [9]:
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [11]:
import sklearn.datasets as skd


In [12]:
iris=skd.load_iris()

In [13]:
diabetes=skd.load_diabetes()

In [14]:
print(iris['DESCR'])


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [34]:
x_iris=pd.DataFrame(iris["data"],columns=iris["feature_names"])

In [36]:
x_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [48]:
y_iris=pd.DataFrame(iris["target"],columns=['tt'])
y_iris

tt
0     0
1     0
2     0
3     0
4     0
..   ..
145   2
146   2
147   2
148   2
149   2

[150 rows x 1 columns]

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [51]:
xtrain,xtest,ytrain,ytest=train_test_split(x_iris,y_iris["tt"],random_state=101,test_size=0.25)

In [52]:
model_iris=LogisticRegression().fit(xtrain,ytrain)

In [56]:
model_iris.score(xtrain,ytrain)

0.9642857142857143

In [55]:
model_iris

LogisticRegression()

In [58]:
model_iris.predict(xtest)

array([0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 1, 1])

In [59]:
pd.to_pickle(model_iris,"flower_species.pkl")

In [62]:
cancer=skd.load_breast_cancer()

In [65]:
print(cancer["DESCR"])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [66]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [72]:
cancer_df=pd.DataFrame(cancer['data'],columns=cancer["feature_names"])

In [98]:
cancer["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [75]:
xtrain,xtest,ytrain,ytest=train_test_split(cancer['data'],cancer["target"],random_state=101,test_size=0.25)

In [76]:
model_cancer=LogisticRegression().fit(xtrain,ytrain)

In [79]:
from sklearn.metrics import classification_report, confusion_matrix


In [81]:
model_cancer.score(xtrain,ytrain)

0.9436619718309859

In [82]:
model_cancer.coef_

array([[ 0.78864608,  0.47002666,  0.28319073, -0.01307598, -0.02615159,
        -0.13330526, -0.18504725, -0.07823241, -0.04670122, -0.0069407 ,
         0.03473276,  0.21353211,  0.09490623, -0.1199291 , -0.00170014,
        -0.03037178, -0.03904016, -0.01044592, -0.01187277, -0.00277035,
         0.84406216, -0.48900407, -0.21285895, -0.01566617, -0.04489127,
        -0.40619539, -0.50503958, -0.14843273, -0.13835901, -0.03894095]])

In [86]:
ypred=model_cancer.predict(xtrain)

print(classification_report(ytrain,ypred))
print(confusion_matrix(ytrain,ypred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92       157
           1       0.95      0.96      0.96       269

    accuracy                           0.94       426
   macro avg       0.94      0.94      0.94       426
weighted avg       0.94      0.94      0.94       426

[[143  14]
 [ 10 259]]


In [87]:
pd.to_pickle(model_cancer,"breast_cancer_detection.pkl")

In [88]:
cancer["feature_names"]

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')